import { createSlice } from "@reduxjs/toolkit";

const GptSlice = createSlice({
  name: "Gpt Slice",
  initialState: {
    isGptPage: false,
    searchResults: [
      [
        {
          adult: false,
          backdrop_path: "/3oamuPpVlwePMPuTdMS6SluHwHa.jpg",
          genre_ids: [18],
          id: 593995,
          original_language: "bn",
          original_title: "Stree",
          overview:
            "During the liberation of India, an old-fashioned man must examine his priorities.",
          popularity: 1.4,
          poster_path: "/1e0n5mPNzYJZ5UDAuoK0qEepU3H.jpg",
          release_date: "1972-07-11",
          title: "Stree",
          video: false,
          vote_average: 9,
          vote_count: 1,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [],
          id: 767586,
          original_language: "hi",
          original_title: "Stree",
          overview:
            "Stree is a 1961 Indian fantasy film selected as the Indian entry for the Best Foreign Language Film at the 34th Academy Awards, but not nominated.",
          popularity: 0.6,
          poster_path: "/mQ19rXBHzeg3s5TbDNmx48NGVuH.jpg",
          release_date: "1961-01-01",
          title: "Stree",
          video: false,
          vote_average: 5,
          vote_count: 1,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [],
          id: 1098714,
          original_language: "or",
          original_title: "Stree",
          overview: "Plot Unavailable.",
          popularity: 0.6,
          poster_path: null,
          release_date: "",
          title: "Stree",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: "/5zMfSDaRprrT6chygNHQeHKafxl.jpg",
          genre_ids: [10751, 28, 12],
          id: 946310,
          original_language: "nl",
          original_title:
            "De Piraten van Hiernaast II: De Ninja's van de Overkant",
          overview:
            "The pirates feel right at home in Sandborough, but the atmosphere cools right down when the ninjas come to live in the street. After all, pirates and ninjas are sworn enemies!  While pirate captain Hector Blunderbuss struggles to get rid of his new neighbours, son Billy and ninja daughter Yuka become friends. The pirates challenge the ninjas to the ultimate battle at the village's annual hexathlon. Who will win the match? Ninjas are faster and more agile of course, but pirates are the best cheats in all of the seven seas...",
          popularity: 23.978,
          poster_path: "/uDsvma9dAwnDPVuCFi99YpWvBk0.jpg",
          release_date: "2022-04-20",
          title: "Pirates Down the Street II: The Ninjas from Across",
          video: false,
          vote_average: 6.551,
          vote_count: 147,
        },
        {
          adult: false,
          backdrop_path: "/jH1f7VaYtMCyqgJRoG7lCg8krxO.jpg",
          genre_ids: [18, 80],
          id: 614488,
          original_language: "fr",
          original_title: "Banlieusards",
          overview:
            "Noumouké, from the suburb of Paris, is about to decide which brother's foot steps to follow - the lawyer student Soulaymaan or the gangster Demba.",
          popularity: 17.955,
          poster_path: "/rhOFpiEDA9S2rmuz5990KBjLgcP.jpg",
          release_date: "2019-10-12",
          title: "Street Flow",
          video: false,
          vote_average: 6.952,
          vote_count: 324,
        },
        {
          adult: false,
          backdrop_path: "/2P0toWq3feNvFAzf28j7vNc1IuZ.jpg",
          genre_ids: [80, 18, 35],
          id: 106646,
          original_language: "en",
          original_title: "The Wolf of Wall Street",
          overview:
            "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
          popularity: 122.117,
          poster_path: "/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg",
          release_date: "2013-12-25",
          title: "The Wolf of Wall Street",
          video: false,
          vote_average: 8.034,
          vote_count: 22448,
        },
        {
          adult: false,
          backdrop_path: "/lKvoDVT5vMFqHyy945OrLq09npC.jpg",
          genre_ids: [18],
          id: 232771,
          original_language: "pt",
          original_title: "Promiscuidade, os Pivetes de Kátia",
          overview:
            "A story of a young woman who is cheating her impotent husband with the surrounding teenagers.",
          popularity: 15.623,
          poster_path: "/u2gju30pxW5KwCt5dWnKxCeAWIz.jpg",
          release_date: "1984-04-30",
          title: "Promiscuity, the Street Kids of Katia",
          video: false,
          vote_average: 5.1,
          vote_count: 10,
        },
        {
          adult: false,
          backdrop_path: "/POvvuyuL2NZzsT8eIigEPOzGkN.jpg",
          genre_ids: [18],
          id: 1034947,
          original_language: "fr",
          original_title: "Banlieusards 2",
          overview:
            "Struggling to overcome cycles of betrayal, revenge and violence, the Traoré brothers continue to fight for a brighter future in a seedy Paris suburb.",
          popularity: 12.21,
          poster_path: "/o2LE7qy5NFnE1tg9OqQ0Pir638n.jpg",
          release_date: "2023-09-27",
          title: "Street Flow 2",
          video: false,
          vote_average: 6.085,
          vote_count: 53,
        },
        {
          adult: false,
          backdrop_path: "/2Gx0IssZeGhpwvULplQuf9UiI26.jpg",
          genre_ids: [16, 12, 9648],
          id: 26662,
          original_language: "ja",
          original_title: "名探偵コナン ベイカー街（ストリート）の亡霊",
          overview:
            "Noah's Ark—the latest in VR technology and a milestone of human innovation—is set for a showcase to Japan's privileged children. They have the honour of beginning a new revolution in gaming; however, their carefree fun is cut short when a company employee is found murdered, with his dying message pointing to a clue hidden within the Ark.  Along with the Detective Boys and Ran Mouri, Conan Edogawa enters Noah's Ark to solve this mystery and ensure the perpetrator is caught. But once they're inside the Ark, it takes on a mind of its own, imprisoning them and the children within its worlds. To escape and bring the murderer to justice, Conan and company must navigate a simulated 19th century London and track down the infamous Jack the Ripper—with the lives of 50 innocent children depending on them.",
          popularity: 16.333,
          poster_path: "/AbgADjLIYoLAc3mayVWGBWSbjT.jpg",
          release_date: "2002-04-20",
          title: "Detective Conan: The Phantom of Baker Street",
          video: false,
          vote_average: 7.669,
          vote_count: 175,
        },
        {
          adult: false,
          backdrop_path: "/g9ROrZey0JYp7kf8DoAyZtKnObj.jpg",
          genre_ids: [27],
          id: 377,
          original_language: "en",
          original_title: "A Nightmare on Elm Street",
          overview:
            "Teenagers in a small town are dropping like flies, apparently in the grip of mass hysteria causing their suicides. A cop's daughter, Nancy Thompson, traces the cause to child molester Fred Krueger, who was burned alive by angry parents many years before. Krueger has now come back in the dreams of his killers' children, claiming their lives as his revenge. Nancy and her boyfriend, Glen, must devise a plan to lure the monster out of the realm of nightmares and into the real world...",
          popularity: 38.136,
          poster_path: "/wGTpGGRMZmyFCcrY2YoxVTIBlli.jpg",
          release_date: "1984-11-09",
          title: "A Nightmare on Elm Street",
          video: false,
          vote_average: 7.323,
          vote_count: 4698,
        },
        {
          adult: false,
          backdrop_path: "/gT6OgUW6fxa8S5pUOZKKIhZe1xX.jpg",
          genre_ids: [18, 27],
          id: 639798,
          original_language: "es",
          original_title: "Malasaña 32",
          overview:
            "Malasaña neighborhood, Madrid, Spain, 1976. While political turmoil ravages the streets all over the country, the Olmedo family arrives in the big city and settles into their new apartment. They soon discover that they are not the only ones roaming its corridors.",
          popularity: 18.797,
          poster_path: "/neCS8vPAtsj9cJDGNaEH76ImSd7.jpg",
          release_date: "2020-01-17",
          title: "32 Malasana Street",
          video: false,
          vote_average: 6.467,
          vote_count: 619,
        },
        {
          adult: false,
          backdrop_path: "/uZeOSnziJHCPSFz9b6JZCrKofqg.jpg",
          genre_ids: [99],
          id: 821406,
          original_language: "en",
          original_title: "All the Streets Are Silent",
          overview:
            "In the late 1980s and early 1990s, skateboarding and hip-hop culture collide in downtown Manhattan. Archival footage from the era showcases the fusion of these two forms of expression.",
          popularity: 4.227,
          poster_path: "/bXDxRoz3S00utOP4FGBRapspm0M.jpg",
          release_date: "2021-09-07",
          title:
            "All the Streets Are Silent: The Convergence of Hip Hop and Skateboarding (1987-1997)",
          video: false,
          vote_average: 6.6,
          vote_count: 7,
        },
        {
          adult: false,
          backdrop_path: "/jjp0pOGBX7b2ZCUwI6U837HiYGS.jpg",
          genre_ids: [27],
          id: 10014,
          original_language: "en",
          original_title: "A Nightmare on Elm Street Part 2: Freddy's Revenge",
          overview:
            "Jesse Walsh moves with his family into the home of the lone survivor from a series of attacks by dream-stalking monster Freddy Krueger. There, Jesse is bedeviled by nightmares and inexplicably violent impulses. It turns out Freddy needs a host body to carry out his gruesome vendetta against the youth of Springwood, Ohio. While Freddy gains influence, Jesse and his girlfriend, Lisa race against the clock trying to figure out what's going on.",
          popularity: 29.46,
          poster_path: "/53kxYw0G3o55yJ23K7s7KMaOyAM.jpg",
          release_date: "1985-11-01",
          title: "A Nightmare on Elm Street Part 2: Freddy's Revenge",
          video: false,
          vote_average: 5.779,
          vote_count: 1688,
        },
        {
          adult: false,
          backdrop_path: "/reMt35KtqTTIy0mhcKA1PfuruDq.jpg",
          genre_ids: [16, 28],
          id: 12613,
          original_language: "ja",
          original_title: "ストリートファイター II MOVIE",
          overview:
            "Bison, the ruthless leader of the international terrorist organization Shadowlaw, has been desperately searching for the greatest fighter on the planet for years. He finds it in Ryu, a young wanderer who never stays in one place long enough for Bison to find him. He does, however, get a fix on Ken Masters, an American martial arts champion who studied with Ryu as a child under the same master. Meanwhile, Major Guile of the United States Army is forced to team up with Chun Li from China in hopes of apprehending Bison and putting a stop his international ring of crime.",
          popularity: 14.4,
          poster_path: "/dZ1rqmE4eIhPbUCr7sn2Pw2wwGW.jpg",
          release_date: "1994-08-06",
          title: "Street Fighter II: The Animated Movie",
          video: false,
          vote_average: 7.046,
          vote_count: 226,
        },
        {
          adult: false,
          backdrop_path: "/kdyYOwpKvvD2fSbwfnMM2YPAzfq.jpg",
          genre_ids: [80, 35, 28],
          id: 187017,
          original_language: "en",
          original_title: "22 Jump Street",
          overview:
            "After making their way through high school (twice), big changes are in store for officers Schmidt and Jenko when they go deep undercover at a local college. But when Jenko meets a kindred spirit on the football team, and Schmidt infiltrates the bohemian art major scene, they begin to question their partnership. Now they don't have to just crack the case - they have to figure out if they can have a mature relationship. If these two overgrown adolescents can grow from freshmen into real men, college might be the best thing that ever happened to them.",
          popularity: 46.935,
          poster_path: "/850chzYHYbT3IISl6Q7dbBuFP2B.jpg",
          release_date: "2014-06-05",
          title: "22 Jump Street",
          video: false,
          vote_average: 6.841,
          vote_count: 7512,
        },
        {
          adult: false,
          backdrop_path: "/fvy3zK7s1x6HTUNK56thXCwPT6v.jpg",
          genre_ids: [28, 16],
          id: 16257,
          original_language: "ja",
          original_title: "ストリートファイターIV 新たなる絆",
          overview:
            "After the fall of Shadaloo, things went quiet and everyone continued with their daily routine. However a new evil is lurking on the horizon and the fighters that battled against Shadaloo must take up arms once again. Meanwhile a mysterious detective, whose motives are unknown, is going to any extent to find the lonesome wanderer Ryu, who appears to play a big part in the scheme of this new evil.",
          popularity: 5.754,
          poster_path: "/x64hBnOpH6Uqd0aDtyGotlNlKjb.jpg",
          release_date: "2009-02-12",
          title: "Street Fighter IV: The Ties That Bind",
          video: false,
          vote_average: 6,
          vote_count: 20,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [10751, 16, 35, 10402, 10770],
          id: 642488,
          original_language: "en",
          original_title: "Mickey's Safety Club: Street Safe, Street Smart",
          overview:
            "Mickey and his friends take a close look at important street safety situations and tips.",
          popularity: 2.801,
          poster_path: "/4pfoP47sMClmkXwYYaUfb8gl08T.jpg",
          release_date: "1989-09-01",
          title: "Mickey's Safety Club: Street Safe, Street Smart",
          video: false,
          vote_average: 9.351,
          vote_count: 37,
        },
        {
          adult: false,
          backdrop_path: "/9mXiLykC4hOO646xpoWUF9uQqBG.jpg",
          genre_ids: [18],
          id: 43255,
          original_language: "ja",
          original_title: "赤線地帯",
          overview:
            "The lives of five prostitutes employed at a Japanese brothel while the nation is debating the passage of an anti-prostitution law.",
          popularity: 11.183,
          poster_path: "/eVKXkGG9xQiVj9kTt9PbdxJJoKS.jpg",
          release_date: "1956-03-18",
          title: "Street of Shame",
          video: false,
          vote_average: 7.7,
          vote_count: 116,
        },
        {
          adult: false,
          backdrop_path: "/vu5Y8qFqlzcboDbbZIMTAgj0KLb.jpg",
          genre_ids: [9648, 27],
          id: 591273,
          original_language: "en",
          original_title: "Fear Street: 1994",
          overview:
            "After a series of brutal slayings, a teen and her friends take on an evil force that's plagued their notorious town for centuries.",
          popularity: 27.689,
          poster_path: "/9J9Wy39ZjrVmfk7yMkulpcI5sy0.jpg",
          release_date: "2021-06-28",
          title: "Fear Street: 1994",
          video: false,
          vote_average: 6.719,
          vote_count: 2069,
        },
        {
          adult: false,
          backdrop_path: "/k3YjcOIpvTvD3EEesHq0J5S79ls.jpg",
          genre_ids: [28, 16],
          id: 17433,
          original_language: "ja",
          original_title: "ストリートファイターZERO",
          overview:
            "Increasingly disturbed by the dark energies building within him, Ryu is confronted by Shun, a boy claiming to be the brother he never knew. But before Ryu can consider whether Shun's timely appearance might be more than coincidental, Shun is kidnapped by Shadowlaw. To recover Shun, Ryu must undertake the ultimate journey of self-discovery and learn to control the power threatening to consume him.",
          popularity: 9.566,
          poster_path: "/k1mZ0gMgSsbdI15tRlFtLYnvXIA.jpg",
          release_date: "1999-12-22",
          title: "Street Fighter Alpha: The Movie",
          video: false,
          vote_average: 6.37,
          vote_count: 77,
        },
      ],
      [
        {
          adult: false,
          backdrop_path: "/yflnRLYid6ySzTaPzoZeZ7cpwkZ.jpg",
          genre_ids: [35, 27, 53],
          id: 19025,
          original_language: "hi",
          original_title: "भूल भुलैया",
          overview:
            "An NRI and his wife decide to stay in his ancestral home, paying no heed to the warnings about ghosts. Soon, inexplicable occurrences cause him to call a psychiatrist to help solve the mystery.",
          popularity: 9.728,
          poster_path: "/soRW3p4GlPphHiFkwbqYGrodQ5S.jpg",
          release_date: "2007-10-12",
          title: "Bhool Bhulaiyaa",
          video: false,
          vote_average: 6.542,
          vote_count: 154,
        },
        {
          adult: false,
          backdrop_path: "/bJcD8d58JWUpHB2tZl7ykDohtJB.jpg",
          genre_ids: [27, 35],
          id: 695962,
          original_language: "hi",
          original_title: "भूल भुलैया 2",
          overview:
            "When strangers Reet and Ruhan cross paths, their journey leads to an abandoned mansion and a dreaded spirit who has been trapped for 18 years.",
          popularity: 9.1,
          poster_path: "/fw0oMHiMt9qOuKEJEmzFiCNAnXc.jpg",
          release_date: "2022-05-20",
          title: "Bhool Bhulaiyaa 2",
          video: false,
          vote_average: 6.202,
          vote_count: 57,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [27, 35],
          id: 980599,
          original_language: "hi",
          original_title: "भूल भुलैया 3",
          overview: "Sequel to the box office hit Bhool Bhulaiyaa 2.",
          popularity: 0.736,
          poster_path: null,
          release_date: "2024-11-01",
          title: "Bhool Bhulaiyaa 3",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
      ],
      [
        {
          adult: false,
          backdrop_path: "/tw2ujWwgZMKt1IqzayqCmnODJvi.jpg",
          genre_ids: [35, 27],
          id: 191562,
          original_language: "hi",
          original_title: "गो गोआ गॉन",
          overview:
            "A rave party off the coast of Goa goes horrifyingly and hilariously wrong when the island is overrun with zombies.",
          popularity: 7.053,
          poster_path: "/pyaAYAifrZ1jAfbdunSAiK0QbKs.jpg",
          release_date: "2013-05-10",
          title: "Go Goa Gone",
          video: false,
          vote_average: 5.722,
          vote_count: 97,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [35, 27, 28, 12],
          id: 534139,
          original_language: "hi",
          original_title: "गो गोआ गॉन 2",
          overview: "",
          popularity: 1.402,
          poster_path: "/ebLaCcHNBmYXPXsCeoYfjsGfeDh.jpg",
          release_date: "",
          title: "Go Goa Gone 2",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
      ],
      [
        {
          adult: false,
          backdrop_path: "/45uCcAUB8Ljz3uKb1y1JHtT5aCT.jpg",
          genre_ids: [12, 28, 53],
          id: 36670,
          original_language: "en",
          original_title: "Never Say Never Again",
          overview:
            "James Bond returns as the secret agent 007 to battle the evil organization SPECTRE. Bond must defeat Largo, who has stolen two atomic warheads for nuclear blackmail. But Bond has an ally in Largo's girlfriend, the willowy Domino, who falls for Bond and seeks revenge.",
          popularity: 27.675,
          poster_path: "/zhoAL4o1STGgLbLxJ9r1ijfyHC9.jpg",
          release_date: "1983-10-07",
          title: "Never Say Never Again",
          video: false,
          vote_average: 6.066,
          vote_count: 1304,
        },
        {
          adult: false,
          backdrop_path: "/zQVYeNyKrdGUU58hZwoFHq7Rn7P.jpg",
          genre_ids: [9648, 27],
          id: 19950,
          original_language: "ta",
          original_title: "யாவரும் நலம்",
          overview:
            "Manohar, along with his family, moves into a new apartment on the 13th floor. However, their peace is disturbed by a spirit that uses the television set as a medium to communicate with them.",
          popularity: 4.267,
          poster_path: "/p5g7U5WISSjHZbjFi2RNdiJ7DjL.jpg",
          release_date: "2009-03-06",
          title: "Yavarum Nalam",
          video: false,
          vote_average: 6.237,
          vote_count: 59,
        },
      ],
      [
        {
          adult: false,
          backdrop_path: "/fpaVxLcSQnnMdtcCRdZV0eTjJPg.jpg",
          genre_ids: [14, 18, 27],
          id: 60898,
          original_language: "cn",
          original_title: "聊齋艷譚",
          overview:
            "Three vixens have meditated for 1,000 years to able to shed their animal natures and become human. For the final month of their rigors, they have moved near a village where women pray to a god of fertility. One sister visits the god's temple and thinks lustful thoughts. As she leaves, a priest confronts her, warning of dire consequences and of demons that will try to stop the vixens' transformation. Soon, the youngest sister saves a poor scholar from bandits and becomes enamored of him. Each sister visits him, and before long, the youth has made love to all three. After they invite him to stay with them, the playfulness takes a scary turn. Where can they turn for help?",
          popularity: 13.074,
          poster_path: "/fTUCwsxVoLFuodAtlL6aITP1B45.jpg",
          release_date: "1990-05-19",
          title: "Erotic Ghost Story",
          video: false,
          vote_average: 6.175,
          vote_count: 63,
        },
        {
          adult: false,
          backdrop_path: "/xHAKGxhi4m4i8e0CQ9UHOLxI9Nr.jpg",
          genre_ids: [35, 14, 10749],
          id: 298099,
          original_language: "cn",
          original_title: "聊齋艷譚之幽媾",
          overview:
            "The soon-to-be Monk Talkative does his best to understand when Fairy Yeh explains what must be done. Rabbit spirits have escaped from the heavenly garden, and must be recaptured. These bunnies can assume human female form, and gorgeous forms at that. One is played by Pang Dan, who happens to be the soon-to-be Monk Talkative's wife. Talkative finds the explanation hard to follow but decides to help.",
          popularity: 6.092,
          poster_path: "/s8wcMzeFJadfbVt40ietjDJ6JAm.jpg",
          release_date: "1997-11-06",
          title: "Erotic Ghost Story: Perfect Match",
          video: false,
          vote_average: 2.3,
          vote_count: 6,
        },
        {
          adult: false,
          backdrop_path: "/7vyzEMfcEpBChEyK7cP6XW6B7hi.jpg",
          genre_ids: [27, 18],
          id: 429417,
          original_language: "en",
          original_title: "Ghost Stories",
          overview:
            "Professor Phillip Goodman devotes his life to exposing phony psychics and fraudulent supernatural shenanigans. His skepticism soon gets put to the test when he receives news of three chilling and inexplicable cases -- disturbing visions in an abandoned asylum, a car accident deep in the woods and the spirit of an unborn child. Even scarier -- each of the macabre stories seems to have a sinister connection to the professor's own life.",
          popularity: 14.351,
          poster_path: "/7a0sai9k5jr7YJRP5S3YIDErMVY.jpg",
          release_date: "2018-01-20",
          title: "Ghost Stories",
          video: false,
          vote_average: 6.463,
          vote_count: 1102,
        },
        {
          adult: false,
          backdrop_path: "/4FFjYrq5v9ynJeKWcOrg3BZKJjD.jpg",
          genre_ids: [27],
          id: 601643,
          original_language: "hi",
          original_title: "Ghost Stories",
          overview: "An anthology of four short horror tales.",
          popularity: 7.941,
          poster_path: "/tQeLzheMNQClBAXy9t1HvZFzhYD.jpg",
          release_date: "2020-01-01",
          title: "Ghost Stories",
          video: false,
          vote_average: 5.045,
          vote_count: 67,
        },
        {
          adult: false,
          backdrop_path: "/1BktiDdArldCQF2QJ2Zhxqwklhc.jpg",
          genre_ids: [18],
          id: 428791,
          original_language: "cn",
          original_title: "鬼叫春",
          overview:
            "The film tells about the sudden death of the marine village girl, she went home by the soul and finding five men to revenge …",
          popularity: 3.117,
          poster_path: "/rclQaUki1gxaHtRpzRYY9nUnC5Q.jpg",
          release_date: "1993-01-01",
          title: "Erotic Ghost Story",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: "/26hdeynra5BGu0z5FnlYxboyMu7.jpg",
          genre_ids: [14, 28],
          id: 30421,
          original_language: "cn",
          original_title: "倩女幽魂",
          overview:
            "Ning Tsai-Shen, a humble tax collector, arrives in a small town to carry out his work. No one is willing to give him shelter for the night, so he ends up in the haunted Lan Ro temple. There, he meets Taoist Swordsman Yen Che-Hsia, and the beautiful Nieh Hsiao-Tsing, with whom he falls in love.",
          popularity: 13.665,
          poster_path: "/pGQy2KB3I0DouwnKNjChyCgULJQ.jpg",
          release_date: "1987-07-18",
          title: "A Chinese Ghost Story",
          video: false,
          vote_average: 7.297,
          vote_count: 241,
        },
        {
          adult: false,
          backdrop_path: "/u7ADiizaAZcD1XbsOG1eFRYjD74.jpg",
          genre_ids: [27, 18, 14],
          id: 105825,
          original_language: "cn",
          original_title: "聊齋三集之燈草和尚",
          overview:
            "The once mighty Tang Dynasty is in its decline. The big land of China is being visited by famine, natural disasters and devils. Chu Chung is such a person. Everywhere he goes, beautiful Suzie follows. So they meet Wick, a monk endowed with magic powers. Chu Chung sees a picture of an exceedingly beautiful girl and falls in love with her. He begs Wick to help him cross the human-spiritual barrier to enter the picture. Chu Chung meets the girl Yi-meng. They make love. Little does Chu Chung realize he has fallen into arch demon Vixen's trap. Unwittingly, he kills the upright god of justice. Suzie helps a repentant Chu Chung escape into the human world. She herself is incarcerated. Wick and Suzie reluctantly help Chu Chung enter the spiritual world again. Righteousness prevails. Vixen loses the war. And Yi-meng is transported to the human world. Unfortunately, Suzie dies. But she may not have died after all...",
          popularity: 12.764,
          poster_path: "/2b1Y6NbZenY45DgC5CwncoLkpo.jpg",
          release_date: "1992-03-05",
          title: "Erotic Ghost Story III",
          video: false,
          vote_average: 5.364,
          vote_count: 10,
        },
        {
          adult: false,
          backdrop_path: "/qOPvylwr2yibx4i2jurMwh9SIRJ.jpg",
          genre_ids: [27, 14],
          id: 78428,
          original_language: "cn",
          original_title: "聊齋艷譚續集：五通神",
          overview:
            "Wutung a sex demon returns in another body where he falls for the mortal girl Hsiao-yen, but heaven thinks otherwise with the girl being burned at the stake and her soul being incarnated in the just born Fang Yu-yin. Anger fills Wutung, and to stop this vengeance the town near his lair promise to offer him a virgin girl at the end of every month to become his sex slave. Ya-Yin is selected; however her lover rescues her from the clutches of Wutung. So Wutung sends his demon concubine to get her back, and to cause havoc on the village for the interference.",
          popularity: 7.288,
          poster_path: "/ighnU4PYk0AQDW9qkD64E5p4hRd.jpg",
          release_date: "1991-01-23",
          title: "Erotic Ghost Story II",
          video: false,
          vote_average: 5.3,
          vote_count: 18,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [27],
          id: 85012,
          original_language: "cn",
          original_title: "猛鬼愛情故事",
          overview:
            "Wong Jing's Classroom follows Ling, the new substitute teacher at a suburban high school. She feels something wrong about her class. The students in her Class 4E are an unruly bunch, except for Don Don, who always sits quietly in the corner. Suspecting that her students Gi Gi, Co Co, and Fong engage in prostitution, Ling reports the problems with her class to the dean, only to be told that there has never been a Class 4E in the school...  In Patrick Kong's Travel, a group of friends go on vacation in Mainland, during which Bo gets killed in a road accident. At Bo's funeral, her travel mates meet Bo's estranged lover Ka Ming , with whom Bo had a heated quarrel on the phone just prior to her tragic death. At the hot-pot dinner after the funeral, a pale-faced Ka Ming reveals to the survivors the secret of his relationship with Bo before going on a killing spree...",
          popularity: 2.255,
          poster_path: "/b7avr37w2mcx2nOziXqGTMHYTcR.jpg",
          release_date: "2011-10-27",
          title: "Hong Kong Ghost Stories",
          video: false,
          vote_average: 3.8,
          vote_count: 6,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [],
          id: 524793,
          original_language: "cn",
          original_title: "網上怪談\u200e",
          overview:
            "There is a rumor that floats around the web. If someone surfs the website www.990714.com, during the Chinese Ghost Festival, they can communicate with the people of the underworld. Seven students succeed in communicating, and reap the consequences. One by one, they each mysterious die. While Han is surfing the website, he hears a knock on the door. It is Tal, a hall-monitor for his school. One night, Tal tells Han that there is another mystery to the site. He reveals that the site can tell you what will happen the next day...",
          popularity: 1.96,
          poster_path: "/qWZRbJmRSNJImMzQSRbprIHQAha.jpg",
          release_date: "2000-01-14",
          title: "Internet Ghost Stories",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [35, 14],
          id: 64530,
          original_language: "cn",
          original_title: "玉女聊齋",
          overview:
            "Chu is a lowly debt collector for the local strongman Wang. Problem is that Chu is too nice/honest/dopey to be very good at the grubby collections job. Chu is treated badly by his boss Wang. Eventually Wang catches one of his twin daughters in the act of seducing the hapless bumpkin Chu. Wang naturally blames Chu rather than the daughter. For punishment Wang sends Chu on an impossible quest to Satan's Temple to steal a statue of Judge Lu.",
          popularity: 7.146,
          poster_path: "/m6y5exiIeJz5L8G5nWdaimdBn3d.jpg",
          release_date: "1998-06-12",
          title: "Chinese Erotic Ghost Story",
          video: false,
          vote_average: 6.5,
          vote_count: 8,
        },
        {
          adult: false,
          backdrop_path: "/duKBdGs7FfCDonUQ9lYLTK131uL.jpg",
          genre_ids: [14, 28, 35],
          id: 9050,
          original_language: "cn",
          original_title: "倩女幽魂II人間道",
          overview:
            "In this installment of a phenomenal saga of the super natural, four young people are caught in a tug-o-war of evil between an Imperial Wizard and a corrupt General. Outrageous special effects galore.",
          popularity: 10.735,
          poster_path: "/uh9xhW3OX77fisjYNhhy4hrUtRZ.jpg",
          release_date: "1990-07-13",
          title: "A Chinese Ghost Story II",
          video: false,
          vote_average: 6.657,
          vote_count: 105,
        },
        {
          adult: false,
          backdrop_path: "/gd9HrzKQt0v9WujF7Zjtd23zc5p.jpg",
          genre_ids: [28, 35, 14],
          id: 9048,
          original_language: "cn",
          original_title: "倩女幽魂III：道道道",
          overview:
            "Set 100 years after the events of A Chinese Ghost Story, Buddhist Bai Yun and his disciple Fong journey through a small town to transport a golden idol of Buddha. However, local thieves thwart their journey, sending them to take shelter at the ghostly Orchid Temple.",
          popularity: 14.282,
          poster_path: "/eh2jmuvX6nHfCcD9ZHt1U1IFUap.jpg",
          release_date: "1991-07-18",
          title: "A Chinese Ghost Story III",
          video: false,
          vote_average: 6.311,
          vote_count: 74,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [27],
          id: 1119842,
          original_language: "ja",
          original_title: "怪談百物語",
          overview:
            '"It really happened!! The definitive version of the mysterious document released by the staff of "Urban Legend"! Practice the fear of a hundred stories handed down from ancient times.',
          popularity: 0.6,
          poster_path: "/eL99jXAPq1K4EgdMGZ7IpUSzqoh.jpg",
          release_date: "2004-05-07",
          title: "100 Ghost Stories",
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [53, 27, 10749],
          id: 444307,
          original_language: "zh",
          original_title: "张震讲故事之合租屋",
          overview:
            "Chang Chen Ghost Stories is a 2016 Chinese romance horror thriller film directed by Zhan Yue.",
          popularity: 0.6,
          poster_path: "/iLyLWevqukHqf8mJgkdKaAhmVyf.jpg",
          release_date: "2016-07-08",
          title: "Chang Chen Ghost Stories",
          video: false,
          vote_average: 6,
          vote_count: 1,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [27, 9648, 53],
          id: 359254,
          original_language: "zh",
          original_title: "张震讲故事之鬼迷心窍",
          overview:
            "Chang Chen Ghost Stories (Chinese: 张震讲故事之鬼迷心窍) is a 2015 Chinese suspense thriller film directed by Zhengchao Xu. It was released on July 3, 2015.",
          popularity: 0.6,
          poster_path: "/jHMkRzb9yeGAQz280jP1XSLwrqt.jpg",
          release_date: "2015-07-03",
          title: "Chang Chen Ghost Stories: Be Possessed by Ghosts",
          video: false,
          vote_average: 5.3,
          vote_count: 3,
        },
        {
          adult: false,
          backdrop_path: "/btq6temupqO10dM4tGQ6RC94sON.jpg",
          genre_ids: [10749, 14],
          id: 660649,
          original_language: "zh",
          original_title: "聊斋之极道天师",
          overview: "",
          popularity: 0.653,
          poster_path: "/f9glhMxpIA789fjvMOmKxXSJaRH.jpg",
          release_date: "2020-01-03",
          title: "Ghost Stories of Extreme Taoist",
          video: false,
          vote_average: 10,
          vote_count: 1,
        },
        {
          adult: false,
          backdrop_path: null,
          genre_ids: [14, 27],
          id: 135806,
          original_language: "ja",
          original_title: "怪談本所七不思議",
          overview:
            "A samurai rescues a mischievous tanuki from hunters and sets it free. When the samurai's wastrel son hatches a plot to kill his father for his fortune, the magical tanuki is determined to protect its rescuer.",
          popularity: 0.931,
          poster_path: "/hCkYFTHrTh5zxa0diFelQUmH4PK.jpg",
          release_date: "1957-07-10",
          title: "Ghost Stories of Wanderer at Honjo",
          video: false,
          vote_average: 7.7,
          vote_count: 3,
        },
        {
          adult: false,
          backdrop_path: "/niWLzDWd3KaE5wxIHDygQB3W0YH.jpg",
          genre_ids: [18, 14],
          id: 404149,
          original_language: "cn",
          original_title: "聊斋荷花三娘子",
          overview: "",
          popularity: 2.608,
          poster_path: "/sBCgpndOpHmmih2GRzclpHbpmIg.jpg",
          release_date: "2009-01-01",
          title: "The Ghost Story: Lotus the Beauty",
          video: false,
          vote_average: 5,
          vote_count: 2,
        },
        {
          adult: false,
          backdrop_path: "/eBR3AjvmtKUnh0nVFRjxJt27Twj.jpg",
          genre_ids: [10402],
          id: 272078,
          original_language: "en",
          original_title: "Coldplay: Ghost Stories",
          overview:
            "In Spring 2014, Coldplay returned with their sixth studio album 'Ghost Stories'. The band unveiled the album to a small handful of fans via an intimate, world-premiere performance at Sony Studios, L.A. This ground-breaking production was performed in the round with jaw-dropping 360-degree and overhead imagery. Director Paul Dugdale explored worlds-within-worlds, blending live performance with cinematic film.",
          popularity: 2.939,
          poster_path: "/qvmBzdLwfAYstwbp1EV9WaOTgjx.jpg",
          release_date: "2014-05-19",
          title: "Coldplay: Ghost Stories",
          video: true,
          vote_average: 9.2,
          vote_count: 8,
        },
      ],
    ],
    searching: false,
  },
  reducers: {
    handleGptPage: (state, action) => {
      state.isGptPage = !state.isGptPage;
    },
    setSearch: (state, action) => {
      state.searching = true;
    },
    setMoviesSearchResults: (state, action) => {
      state.searchResults = action.payload;
      state.searching = false;
    },
  },
});

export const { handleGptPage, setSearch, setMoviesSearchResults } =
  GptSlice.actions;
export default GptSlice.reducer;
